### ISSUE TITLE
[feat] Add command to remove point from freehand bspline

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tomate44/CurvesWB#106]
Currently users can add points in freehand bsplines by pressing the `i` key, but it seems that there's no option to remove points from them.

**Comment by tomate44** [comment]
"Suppr" key deletes a point.

**Comment by Anthony-Gaudino** [comment]
On MacBooks one needs to use `fn` + `backspace`.
`backspace` alone doesn't work.
