### ISSUE TITLE
Create gordon surface fails

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tomate44/CurvesWB#107]
On following example file, trying to create a gordon surface using the curves that form a closed section fails.

[create_gordon_surface_fail.FCStd.zip](https://github.com/tomate44/CurvesWB/files/13677313/create_gordon_surface_fail.FCStd.zip)

**Comment by tomate44** [comment]
Input Curve objects should form a grid-like pattern.
So only 4 outer curves are allowed.
