### ISSUE TITLE
Using parametric solid with Gordon surfaces often fails to join surfaces

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tomate44/CurvesWB#110]
I have been working on a part that requires complex shapes and have been trying to use gordon surfaces, but they often fail to join into a shell or solid, I had to use the surfaces from the Surface instead as these were more likely to work.

Here's one example that fails:  [join_gordon_surfaces.FCStd.zip](https://github.com/tomate44/CurvesWB/files/13780435/join_gordon_surfaces.FCStd.zip)

**Comment by tomate44** [comment]
Gordon surfaces involve approximation, so tight enough joins are not guaranteed.
