### ISSUE TITLE
Curves uses an outdated numpy

### ISSUE THREAD

**Issue by packocrayons** [tomate44/CurvesWB#114]
Numpy has deprecated the "np.typeDict" for np.sctypeDict. This throws an error unless an older version of numpy is installed.

I think the package installs an older numpy version, but I updated numpy for other work on this machine and that broke the curves wb.

SO question about it (for tensorflow, but same idea)
https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict

**Comment by tomate44** [comment]
CurvesWB doesn't install any python package.
CurvesWB doesn't use np.typeDict
