### ISSUE TITLE
Sketch On Surface only projects Bsplines of up to order 6

### ISSUE THREAD

**Issue by meutzitzu** [tomate44/CurvesWB#116]
Steps to reproduce: Create a curved surface
use Sketch On Surface
sketch any desired geometry
also sketch a B-spline of 8 or more control points

exit sketch

problem: Any other geometry will appear on the curved surface, but the 7th or more order B-Spline curve does not appear. There is no easily noticeable error

**Comment by tomate44** [comment]
This should be fixed with FreeCAD Commit [1a2e922](https://github.com/FreeCAD/FreeCAD/commit/1a2e922dce6167faca6c69f660d9e48521fb6a01)
