### ISSUE TITLE
Compatibility with V0.17 Part Design workflow

### ISSUE THREAD

**Issue by darahan** [tomate44/CurvesWB#12]
Hi, I am trying to use your workbench to create a feature in a part I am designing, with the rest of the geometry designed in the new V0.17 Part Design workbench. In a discussion on the forum with ChrisG it arose that both workbenches do not have compatibility with each other. How can this be resolved? I am willing to cooperate on this.

**Comment by luzpaz** [comment]
@tomate44 is this issue valid or `wontfix` ?
