### ISSUE TITLE
curves WB - cannot join curves a blend curve it's 2 curves

### ISSUE THREAD

**Issue by thecoolsundar** [tomate44/CurvesWB#123]
When I try to join a blend curve to the 2 curves it was generated from, the operation fails with 'unknown exception while reading attribute 'curve' of object 'toposhape'

OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37839 (Git) Snap 1057
Build type: Release
Branch: main
Hash: 9b547bb90fbdf5f9e6df17fee640566cbe2ab37e
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/India (en_IN)
Installed mods: 
  * CurvedShapes 1.0.9
  * Curves 0.6.37

**Comment by tomate44** [comment]
This should be fixed in version 0.6.44
