### ISSUE TITLE
[feature] Sketch on multiple surfaces

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tomate44/CurvesWB#127]
Currently the `Sketch on surfaces` tool only allows adding a sketch to a single surface.

I propose extending this tool to allow adding a sketch to multiple connected surfaces simultaneously.

My current workaround is to try to create a single surface using `Gordon surface` or the tools from the Surface workbench and then use `Sketch on surfaces` on that, but these usually result in a surface that will not perfectly match the original surfaces.

**Comment by tomate44** [comment]
SketchOnSurface uses a UV mapping on the parametric space of the target face.
So, it cannot be generalized to multiple connected faces that have different parametric spaces.
I close.
