### ISSUE TITLE
Mapping circle to cone and setting thickness doesn't work right

### ISSUE THREAD

**Issue by theosib** [tomate44/CurvesWB#131]
Steps:
- Install the Curves workbench
- Go to Part workbench
- Create a cone; leave its values at default
- Select the side of the cone
- Go to Curves
- Select Sketch on surface
- Open the sketch
- Draw a circle in the middle of it
- Go back to the Sketch_On_Surface object
- Set the thickness to 1

Expected:
I should see something cylinder-like sticking out of the cone.

Actual results
It's all twisted up in ways that only an image could convey.

Please also see the FCStd file attached. Also see: https://github.com/FreeCAD/FreeCAD/issues/16013

<img width="491" alt="image" src="https://github.com/user-attachments/assets/2cc27632-c025-4e03-9ede-db75b4ed0aa0">

[curve sketch on cone.FCStd.zip](https://github.com/user-attachments/files/16719509/curve.sketch.on.cone.FCStd.zip)

**Comment by theosib** [comment]
Setting the offset to something other than zero makes it work right.

**Comment by theosib** [comment]
Someone on Discord can get this to work with an offset of zero. But I can't. He and I are both using dev version 38459. I'm betting he and I are on different platforms (I'm on Mac), and compiler optimizer differences are resulting different floating point rounding errors.

**Comment by theosib** [comment]
Changing the offset doesn't fix everything. Here's a sketch that doesn't "thickness" right no matter what. 
[sketch on cone.FCStd.zip](https://github.com/user-attachments/files/16719819/sketch.on.cone.FCStd.zip)

**Comment by theosib** [comment]
And here's another that doesn't come out right.
[sketch on cone2.FCStd.zip](https://github.com/user-attachments/files/16719845/sketch.on.cone2.FCStd.zip)

**Comment by tomate44** [comment]
This should be fixed in 0.6.47
Please re-open and comment if it is not.
