### ISSUE TITLE
Is Curves addon ready for 1.0 release?

### ISSUE THREAD

**Issue by luzpaz** [tomate44/CurvesWB#136]
Per [blog](https://blog.freecad.org/2024/08/30/1-0rc1-is-coming-next-week-lets-update-addons/) RC1.0 phase is occurring and we're encouraging addon developers to make sure their addons are compatible.

https://github.com/FreeCAD/FreeCAD-addons/issues/305

**Comment by luzpaz** [comment]
cc @tomate44

**Comment by tomate44** [comment]
I use self-compiled FC main branch.
So, Yes, it is.
