### ISSUE TITLE
Flatten Surface is skewed in Freecad 1.1.0 dev

### ISSUE THREAD

**Issue by wanderingwaldo2** [tomate44/CurvesWB#137]
When using the flatten surface feature on a truncated conical surface the output was skewed.

**Comment by wanderingwaldo2** [comment]
![Skew_Issue](https://github.com/user-attachments/assets/f22adf32-1711-434e-a440-dfabe4e43c07)
Here is a picture of the issue.

**Comment by tomate44** [comment]
Do you have an example file please ?

**Comment by wanderingwaldo2** [comment]
I have attached an example file with the skewed output.

**Comment by tomate44** [comment]
Where ? I cannot find it.

**Comment by wanderingwaldo2** [comment]
[FlattenFailExample.zip](https://github.com/user-attachments/files/17078983/FlattenFailExample.zip)

Looks like it wasn't a supported file type for upload.  This should work.

**Comment by tomate44** [comment]
Did you update CurvesWB to latest version before posting this bug report ?
For me, Flatten Face works fine with your file.
```
OS: Manjaro Linux (KDE/plasmawayland)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38782 (Git)
Build type: Release
Branch: main
Hash: 8b9f5bdc4f4bd3cf4a440365fcc7cbcd2afe8580
Python 3.12.5, Qt 6.7.2, Coin 4.0.2, Vtk , OCC 7.8.2.dev
Locale: French/France (fr_FR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/breeze
Installed mods: 
  * CurvesWB 0.6.47

```

**Comment by wanderingwaldo2** [comment]
Sorry, I had the addon manager set to automatically update and thought that happened in the background, but once I opened the addon manager just now it updated and the flatten face command works.

**Comment by tomate44** [comment]
Fine. Good news.
