### ISSUE TITLE
Updating Curves WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [tomate44/CurvesWB#15]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
@tomate44 quick question: what's the status on this?

**Comment by tomate44** [comment]
I use Py3/Qt5 builds since several months, so I think it can be declared "Py3/Qt5 compatible".
Thanks.

**Comment by luzpaz** [comment]
Thanks!
