### ISSUE TITLE
NO Module named BOPTools.SplitAPI

### ISSUE THREAD

**Issue by bisechen** [tomate44/CurvesWB#3]
![clipboard-1](https://cloud.githubusercontent.com/assets/18411296/24539819/df9d06ba-1622-11e7-9c3b-e3b72480b325.jpg)

hello~
I'm having problems, what am I missing?

**Comment by tomate44** [comment]
Hello,
BOPTools are only available in the current FreeCAD devel source tree (0.17).
Also, please not that my workbench is very poorly coded, full of bugs and half-finished tools.
Use it at your own risk (not for real work, please) and feel free to ask if you need help or information.
