### ISSUE TITLE
Error when trying to delete a Sketch On Surface

### ISSUE THREAD

**Issue by 0penBrain** [tomate44/CurvesWB#31]
When trying to delete a Sketch On Surface object (select in the Tree View and hit 'Del' key), the object isn't deleted and following error raises in the report view :

> Traceback (most recent call last):
>   File "/home/OB/.FreeCAD/Mod/Curves/Sketch_On_Surface.py", line 340, in onDelete
>     self.children.ViewObject.Visibility = True
> <class 'AttributeError'>: 'list' object has no attribute 'ViewObject'

**Comment by tomate44** [comment]
Seems to be fixed now. Thanks
