### ISSUE TITLE
0.18 incompatibility?

### ISSUE THREAD

**Issue by DeepSOIC** [tomate44/CurvesWB#33]
Part.Feature has no attribute "getSubObject"
https://forum.freecadweb.org/viewtopic.php?f=3&t=49978&start=10#p429690

**Comment by tomate44** [comment]
Thanks for reporting.
This should be [fixed](https://github.com/tomate44/CurvesWB/commit/8970de529c9ccc8fe048fb74f69769abd0e5c9ea) now.
