### ISSUE TITLE
Screenshots + other things

### ISSUE THREAD

**Issue by luzpaz** [tomate44/CurvesWB#5]
Thanks for your work on this addon. I'm volunteering to improve the addon manager. Would you mind:

- [x] adding some screenshots of your addon  
- [x] tagging this repo with the 'freecad' tag  
- [x] stating what freecad versions this addon is compatible with  
- [x] if this is compatible with latest 0.17 version please inform users they can now download addon through the new addon manager  
- [x] offering a FreeCAD forum link for folks to ask/discuss issues related to this addon  

Thanks!

**Comment by tomate44** [comment]
Hi,
Indeed my addon is totally undocumented.
It is time for a little bit of work in this area.
I'll do it when I get some time.
Thanks for your work on the bugtracker ( and now the addon manager !).

**Comment by luzpaz** [comment]
👍 
I'm happy to help as well. Just point me to some more info.

**Comment by luzpaz** [comment]
@tomate44 can you add https://forum.freecadweb.org/viewtopic.php?f=8&t=22675 to the README as the forum thread for people to post on to ask/discuss all things CurvesWB ?
