### ISSUE TITLE
Reverse flag in Blend curve doesn't honor parameter set to 0 mm

### ISSUE THREAD

**Issue by janbraiins** [tomate44/CurvesWB#55]
I have come across a small issue. My scenario:

- I want to connect 2 curves with the blend curve feature
- I want to use 0 mm for both parameters, so that the blended curve is agnostic to changes in lengths of both curves
- This requires having one of the ends set in 'reverse' direction
The problem:
- setting the parameter 0 mm doesn't switch the blend point to the other end of the curve = 0mm always means only one end of the curve, which I believe is not expected.
I am attaching a small example where I have set the parameter 1 to 0.001 mm which actually works. Try setting it 0, it would jump to the other end of the curve.

Still want to thank you for this excellent workbench.

Jan

Below are screenshots of the scenario with the 0.001 mm workaround
![image](https://user-images.githubusercontent.com/8446970/143770987-bc8f43dc-2916-45e8-aa51-071979e7f7d7.png)
![image](https://user-images.githubusercontent.com/8446970/143770993-bbd284b3-6ddb-448c-8752-08d7de3f7717.png)
Switching to 0 mm:
![image](https://user-images.githubusercontent.com/8446970/143771034-0af81451-f2f5-4c12-914d-f227bf5d377d.png)
![image](https://user-images.githubusercontent.com/8446970/143771021-cba5fd65-73b9-4239-85e5-44c7533f3e57.png)

**Comment by tomate44** [comment]
It should be fix with [commit](https://github.com/tomate44/CurvesWB/commit/6a1cf9c4f179d7aee7ebbc3638e0ac448764696b). 
Thanks for the report.
I close.

**Comment by janbraiins** [comment]
thank you for a swift fix ;-)
