### ISSUE TITLE
[FR] increase (Select adjacent faces)

### ISSUE THREAD

**Issue by hamza00789** [tomate44/CurvesWB#63]
Point Selection   

usage 
  
All connected faces will be selected from the point selection (Tangent or non Tangent) 
 
Example 

![1](https://user-images.githubusercontent.com/92737149/152429330-58235607-49da-44d0-beed-5592fc3eff89.jpg) 

![2](https://user-images.githubusercontent.com/92737149/152429349-e6e2c0d8-7a79-4825-82f2-6158e6b309cf.jpg)
      
Tangent Selection   

usage 

In the tangent selection, all connected faces that are tangent with each other will be selected. 

Example         

![3](https://user-images.githubusercontent.com/92737149/152429590-528b5115-05cc-47a8-a7a2-46a1b09fa4f2.jpg) 

![4](https://user-images.githubusercontent.com/92737149/152429613-98171c38-4b39-454f-8a6f-2507b457fa26.jpg)

Invert selection   
 
usage 

The invert selection will select all faces except the one selected. (Tangent or non Tangent)

Example 

![5](https://user-images.githubusercontent.com/92737149/152429761-0c88f4c6-2a45-459c-8c7c-1b86368b17f8.jpg) 

![6](https://user-images.githubusercontent.com/92737149/152429768-1b2e2648-7829-4a44-8d08-b12995dbb5cf.jpg)

**Comment by luzpaz** [comment]
Can you x-post to the [dedicated forum thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=22675) and x-post the URL back here? TIA

**Comment by luzpaz** [comment]
@hamza00789 please stop closing and reopening this ticket.
