### ISSUE TITLE
flatten face

### ISSUE THREAD

**Issue by sasobadovinac** [tomate44/CurvesWB#69]
Just a reminder to possibly include the flatten_face.FCMacro as a tool in Curves WB, as discussed in the forum...

https://forum.freecad.org/viewtopic.php?p=582967#p582967 (topic)
https://forum.freecad.org/viewtopic.php?p=387511#p387511 (latest version of the macro)

**Comment by tomate44** [comment]
Flatten Tool[](https://github.com/tomate44/CurvesWB/commit/89ccc2c1f4fd20a4bece23c974fc7cb3b81242f0)
