### ISSUE TITLE
bug of Sketch_on_Surface - straight lines missing, only splines are ok

### ISSUE THREAD

**Issue by rejnok93** [tomate44/CurvesWB#74]
For this certain project (FCStd file attached) - trying to put Text on Cilinder, but result is wrong, all straight lines are missing:
![bug_freecad_curves_workbench_sketch_on_surface.png](https://user-images.githubusercontent.com/26550337/190714367-75d11302-0cc2-4213-92b5-96448b9947c7.png)
Original text is  `D+T ♥ 15.7.2017`
[darek_vaza_textonly2_sosbad.FCStd.zip](https://github.com/tomate44/CurvesWB/files/9586681/darek_vaza_textonly2_sosbad.FCStd.zip)
[Arial.ttf.zip](https://github.com/tomate44/CurvesWB/files/9586730/Arial.ttf.zip)
copy of console log:
![log_screenshot.png](https://user-images.githubusercontent.com/26550337/190715096-4fb488d8-8aba-45a6-95cb-141d63747f52.png)
FreeCAD v0.20-1 (macOS 10.13.6), Curves Workbench installed from Addons Manager today (actual version)

**Comment by tomate44** [comment]
It works OK here.
![SkOnSurf](https://user-images.githubusercontent.com/19555735/191711565-e5987944-2f09-4672-86c6-56ef187606e4.png)

**Comment by luzpaz** [comment]
@tomate44 [About](https://wiki.freecad.org/About) info ?
