### ISSUE TITLE
Blend Surface and Bland Solid error

### ISSUE THREAD

**Issue by rafaljot** [tomate44/CurvesWB#77]
WB Blend Surface and Bland Solid  seems to be a great toolset. However, it looks like it doesn't work properly in certain situations. Several pairs of surfaces were connected correctly while one was not

<img width="1410" alt="Zrzut ekranu 2023-02-2 o 00 04 04" src="https://user-images.githubusercontent.com/13086437/216186083-80d46a10-663d-4779-91aa-ee948a867261.png">
[WB sample.FCStd.zip](https://github.com/tomate44/CurvesWB/files/10562766/WB.sample.FCStd.zip)

**Comment by luzpaz** [comment]
please drag/drop zip file in to this issue for it to attach, thanks

**Comment by rafaljot** [comment]
Sure. 
[WB sample 2.FCStd.zip](https://github.com/tomate44/CurvesWB/files/10663437/WB.sample.2.FCStd.zip)

**Comment by rafaljot** [comment]
It looks as if he led the tangents to the next corners.
<img width="671" alt="Zrzut ekranu 2023-02-2 o 00 04 04" src="https://user-images.githubusercontent.com/13086437/216985348-2da3f099-56a1-4b81-9514-3d638bcb3166.png">

**Comment by rafaljot** [comment]
any idea?

**Comment by luzpaz** [comment]
cc @tomate44

**Comment by tomate44** [comment]
Should be fixed in new version 0.6.15

**Comment by rafaljot** [comment]
Yes, now it works.

<img width="533" alt="Zrzut ekranu 2023-11-28 o 22 33 28" src="https://github.com/tomate44/CurvesWB/assets/13086437/b8aa2139-bc97-4433-81b4-cb944ac5b303">
