### ISSUE TITLE
sketch on surface does not work on double bent surfaces 

### ISSUE THREAD

**Issue by woecj** [tomate44/CurvesWB#82]
Mapped surface is calculated wrong, if the surface is bent into two directions.
For example, if I use a zylinder having a bent outer surface, the mapped sketch is calculated to a very small area having nothing to do with the surface selected.
Mapping is ok, if the surface is flat zylindric.

Systeminfo: FreeCad 0.20.2 on debian linux (bookworm), curves workbench 0.6.8 - same behavior using the appimage downloaded from freecad server.

![cylinder-part-doublebent](https://user-images.githubusercontent.com/109601524/231685969-dc1f2f75-b4b4-4d44-b68f-72a5126e3878.png)
![mapped-sketch](https://user-images.githubusercontent.com/109601524/231685977-fb1e843e-10d8-4bd6-9ee2-ec323a9b05f1.png)

**Comment by edwilliams16** [comment]
You should upload a file illustrating the problem.  Rename .FCStd to .zip
