### ISSUE TITLE
Can't delete split curve

### ISSUE THREAD

**Issue by Anthony-Gaudino** [tomate44/CurvesWB#99]
In this minimal file if I split `JoinCurve011` and then double click on it on panel to edit it and move the point and then press `q` to exit edit mode, `JoinCurve011` appears marked in yellow and if I try to delete `JoinCurve011` nothing happens.
I need to double click on `JoinCurve011` again to be able to delete it.

`Freehand_Bspline` doesn't have this issue.
[curve_bug.FCStd.zip](https://github.com/tomate44/CurvesWB/files/13628882/curve_bug.FCStd.zip)

**Comment by tomate44** [comment]
This should be fixed in 0.6.50
